### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mchalupa** [ista-vamos/hna#1]
## HNL
- [x] turn to event-driven so that we can use it from HNA
- [x] cache atoms results
- [x] fix the case when one side of atom has no variable
- [x] add functions
- [ ] use prefix trees (automata)
- [ ] profile and optimize

## HNA
- [x] implement slices
- [x] implement the monitoring algorithm

## General
- [ ] connect to vamos sources (now we have only CSV files)
